# Generated by Django 3.2.7 on 2022-01-13 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeofworkout',
            options={'verbose_name_plural': 'Types of workout'},
        ),
        migrations.AlterModelOptions(
            name='workoutroutine',
            options={'verbose_name_plural': 'Workout routines'},
        ),
        migrations.RenameField(
            model_name='workoutroutine',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='workoutroutine',
            old_name='Duration',
            new_name='duration',
        ),
    ]
