# Generated by Django 3.2.7 on 2022-01-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_auto_20220113_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('type_of_workout', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.RemoveField(
            model_name='workoutroutine',
            name='type_of_workout',
        ),
        migrations.DeleteModel(
            name='TypeOfWorkout',
        ),
        migrations.DeleteModel(
            name='WorkoutRoutine',
        ),
    ]
