# Generated by Django 3.2.7 on 2022-01-13 21:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0004_user_workouts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_workouts',
            name='user',
        ),
        migrations.AddField(
            model_name='user_workouts',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
