# Generated by Django 3.2.7 on 2022-01-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('workouts', '0006_auto_20220114_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='users',
        ),
        migrations.AddField(
            model_name='workout',
            name='users',
            field=models.ManyToManyField(to='profiles.UserProfile'),
        ),
    ]
