# Generated by Django 3.2.7 on 2022-01-14 09:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_auto_20220114_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 15, 9, 16, 10, 699209, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='workout',
            name='locations',
            field=models.CharField(default='online', max_length=250),
        ),
        migrations.AlterField(
            model_name='workout',
            name='type_of_workout',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
