# Generated by Django 3.2.7 on 2022-01-14 09:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('workouts', '0008_auto_20220114_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='locations',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 15, 9, 19, 29, 204367, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='workout',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to='profiles.UserProfile'),
        ),
    ]
