# Generated by Django 3.2.7 on 2022-01-18 10:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('workouts', '0009_auto_20220114_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 19, 10, 26, 13, 643541, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='workout',
            name='users',
            field=models.ManyToManyField(blank=True, to='profiles.UserProfile'),
        ),
    ]
