# Generated by Django 3.2.7 on 2022-01-18 11:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0010_auto_20220118_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 19, 11, 37, 53, 889203, tzinfo=utc)),
        ),
    ]
