# Generated by Django 3.2.7 on 2022-01-20 16:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0013_alter_workout_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='workout',
            name='time',
            field=models.CharField(default='12:00', max_length=250),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 21, 16, 13, 34, 84329, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='workout',
            name='type_of_workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.typeofworkout'),
        ),
    ]
