# Generated by Django 3.2.7 on 2022-01-20 16:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0014_auto_20220120_1613'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TypeOfWorkout',
            new_name='Type_Of_Workout',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='time',
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 21, 16, 15, 31, 298253, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='workout',
            name='type_of_workout',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
