# Generated by Django 3.2.7 on 2022-01-20 16:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0016_auto_20220120_1618'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type_Of_Workout',
            new_name='TypeOfWorkout',
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 21, 16, 42, 47, 644216, tzinfo=utc)),
        ),
    ]
