# Generated by Django 3.2.7 on 2022-01-20 16:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0017_auto_20220120_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 21, 16, 47, 48, 354515, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='workout',
            name='type_of_workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.typeofworkout'),
        ),
    ]
