# Generated by Django 3.2.7 on 2022-01-24 14:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0018_auto_20220120_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 25, 14, 33, 8, 715303, tzinfo=utc)),
        ),
    ]
