# Generated by Django 3.2.7 on 2022-01-27 14:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0020_alter_workout_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 28, 14, 52, 24, 930991, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='workout',
            name='duration',
            field=models.CharField(max_length=250),
        ),
    ]
