# Generated by Django 3.2.7 on 2022-01-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0025_alter_workout_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='workout',
            name='duration',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='workout',
            name='location',
            field=models.CharField(max_length=250),
        ),
    ]
