# Generated by Django 3.2.7 on 2022-02-10 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0025_alter_workout_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='workout',
            name='duration',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Input must be numeric', regex='^[0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='workout',
            name='location',
            field=models.CharField(max_length=250),
        ),
    ]
