# Generated by Django 3.2.7 on 2022-02-01 13:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0027_alter_workout_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='duration',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Input must be numeric', regex='^[0-9]*$')]),
        ),
    ]
