# Generated by Django 3.2.7 on 2022-02-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0027_rename_type_of_workout_workout_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='time',
            field=models.TimeField(default='12:00'),
        ),
    ]
